### ISSUE TITLE
Not able to setup d2 for mkdocs

### ISSUE THREAD

**Issue by developer-lfdsystems** [landmaj/mkdocs-d2-plugin#27]
Hi,

I am creating a mkdocs docker container using the below configurations

**Dockerfile:**
```
FROM squidfunk/mkdocs-material
RUN pip install mkdocs-d2-plugin

```
**docker-compose.yml:**
```yaml
version: '3'
services:
  mkdocs:
    build: .
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
```

I have created the docs folder as well as created the below config
**mkdocs.yml**
```yaml
site_name: LFD System Documentation
site_description: Documentation for the LFD System Organization
site_author: LFD Systems

nav:
  - Home: index.md
  - About: about.md

theme:
  name: 'material'

plugins:
  - d2:
      executable: d2 # path to d2 executable
      cache: True
      cache_dir: .config/plugin/d2
      layout: dagre
      theme: 0
      dark_theme: -1
      sketch: False
      pad: 100
      scale: -1.0
      force_appendix: False
      target: "''"
```

But, I am getting the below error in the Docker container
```
ERROR   -  [11:41:53] An error happened during the rebuild. The server will appear stuck until build errors are resolved.

INFO    -  Building documentation...

INFO    -  mkdocs-d2-plugin: Using cache at .config/plugin/d2/db (dbm.gnu)

Error: executable 'd2' not found
```
